### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by Amrit131** [Amrit131/portfolio-mobile#10]
https://github.com/Amrit131/portfolio-mobile/blob/5e05e17db5bfbad77dede3065a5b348a5d8b3767/style.css#L1-L59

**Comment by Mutai-Gilbert** [comment]
I think you should align the margin to the left on the projects development cards just as the paragraph.

**Comment by tonnytech** [comment]
Maybe you should consider reducing the margin top of the recent works heading to the number of pixels used in the figma template

**Comment by JNC26** [comment]
I noticed your cards aren't aligned to the left. Please do so. Happy coding
