### ISSUE TITLE
Tool-bar section

### ISSUE THREAD

**Issue by Amrit131** [Amrit131/portfolio-mobile#8]
https://github.com/Amrit131/portfolio-mobile/blob/d9f5246eb4be38e07e80a2b3048a2b79c76924d3/style.css#L623-L678

**Comment by LDouglasOT** [comment]
Code looks good and clean, Keep up the good work, Kudos to you.

**Comment by akos29** [comment]
### Hello Amrit
Approved! 
#
@Amrit131 You did a great job.

**Comment by akhror-valiev** [comment]
- Good job! clean code and a responsive web page
